### PR TITLE
Article list page

### PR DESCRIPTION
**Pull request by dazld**
fixes https://github.com/enoughrec/arecordlabel/issues/39

# Don't merge me!

- New Article list and Article display
- new tag title and display when filtering

# tag display when filtering
screen shot 2015-01-31 at 12 42 41
screen shot 2015-01-31 at 12 27 32

# article list
screen shot 2015-02-01 at 01 20 32

# article

screen shot 2015-01-25 at 02 30 01

### CODE REVIEW

**Comment by dazld** [comment]
@psenough what other meta data would you like on the articles?

**Comment by psenough** [comment]
seems about right, can only think of date and title. i'm the only person writing the articles anyways, so i don't really see the need for authorship

**Comment by dazld** [comment]
no need for tags...?

**Comment by dazld** [comment]
I put tags on the metadata, but not currently using them. 

The listing page tries to get the following data from the articles:
- image: source for the first img tag in the article
- description: the text from the first paragraph in the article
- reading time (like on medium) in minutes
- articles sorted by date, most recent first
- link is a slugified version of the article title, lowercased

also, have updated the redirection to happen on the server, so search engines get proper 301s to the new urls. so so good that we have mod_rewrite now - can do lots with this. was thinking would have to do this in an index.php file, but in the end htaccess works just as well.

however, could implement a homepage in php that looks for crawler user agents (facebook, being the biggest one that I'm worried about) and supplies correct meta info for the share action.

**Comment by psenough** [comment]
all sounds lovely :)

**Comment by dazld** [comment]
@psenough do you want to port more articles across, or can I merge this when I'm ready?

**Comment by psenough** [comment]
i haven't checked your branch yet, but i trust you, you can merge, i'll add
more articles later during the week :)

**Comment by dazld** [comment]
okie, going to go ahead and merge.

**Comment by dazld** [comment]
@psenough merged and deployed! let's see how it goes, if anything does break it's easy enough to rollback until it's right. play with it, and lets jam on the styles / functions a bit, see if there's anything missing.

**Comment by psenough** [comment]
just checked it now, looks pretty good :) thanks a million dan!

**Pull request merged**
